sudo: false
language: python
python:
- 2.7
install:
- sudo apt-get -qq update
- pip install -r requirements.txt
- pip install codecov youtube-dl pushbullet.py
- sudo apt-get install libav-tools
script:
- coverage run tests.py
after_success:
- codecov
before_install:
- openssl aes-256-cbc -K $encrypted_bf079a563187_key -iv $encrypted_bf079a563187_iv
  -in config.yml.enc -out config.yml -d
