---
path: PATH
users:
    - username: USERNAME
      password: PASSWORD
      notify_via_pushbullet: True
      pushbullet_token: TOKEN

# If you want more users just add more of these blocks

#    - username: USERNAME2
#      password: PASSWORD2
#      notify_via_pushbullet: True
#      pushbullet_token: TOKEN2
